package ryhma.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ryhma.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.23 21:38:53 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JasenTest {



  // Generated by ComTest BEGIN
  /** testToString49 */
  @Test
  public void testToString49() {    // Jasen: 49
    Jasen jasen = new Jasen(); 
    jasen.parse(" 1 | 1 | Ankka Aku | 13 |"); 
    assertEquals("From: Jasen line: 52", true, jasen.toString().startsWith("1|1|Ankka Aku|13|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse81 */
  @Test
  public void testParse81() {    // Jasen: 81
    Jasen jasen = new Jasen(); 
    jasen.parse(" 1 | 1 | Ankka Aku | 13 |"); 
    assertEquals("From: Jasen line: 84", true, jasen.toString().startsWith("1|1|Ankka Aku|13|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi234 */
  @Test
  public void testRekisteroi234() {    // Jasen: 234
    Jasen aku1 = new Jasen(); 
    Jasen aku2 = new Jasen(); 
    assertEquals("From: Jasen line: 237", 0, aku1.getTunnusNro()); 
    aku1.rekisteroi(); 
    assertEquals("From: Jasen line: 239", 5, aku1.getTunnusNro()); 
    aku2.rekisteroi(); 
    aku2.rekisteroi(); 
    assertEquals("From: Jasen line: 242", 7, aku2.getTunnusNro()); 
  } // Generated by ComTest END
}