package ryhma.test;
// Generated by ComTest BEGIN
import java.io.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import ryhma.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.24 20:00:44 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RekisteriTest {


  // Generated by ComTest BEGIN  // Rekisteri: 24

   private Rekisteri rekisteri; 
   private Ryhma ryhma1; 
   private Ryhma ryhma2; 
   private int jid1; 
   private int jid2; 

   public void alustaRyhma() {
     rekisteri = new Rekisteri(); 
     ryhma1 = new Ryhma(); ryhma1.taytaRyhmaTiedoilla(); ryhma1.rekisteroi(); 
     ryhma2 = new Ryhma(); ryhma2.taytaRyhmaTiedoilla(); ryhma2.rekisteroi(); 
     jid1 = ryhma1.getTunnusNro(); 
     jid2 = ryhma2.getTunnusNro(); 
     try {
     rekisteri.lisaa(ryhma1); 
     rekisteri.lisaa(ryhma2); 
     } catch ( Exception e) {
        System.err.println(e.getMessage()); 
     }
   }
  // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa83 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa83() throws SailoException {    // Rekisteri: 83
    var rekisteri = new Rekisteri(); 
    Ryhma ry1 = new Ryhma(), ry2 = new Ryhma(); 
    ry1.rekisteroi(); ry2.rekisteroi(); 
    assertEquals("From: Rekisteri line: 88", 0, rekisteri.getRyhmia()); 
    rekisteri.lisaa(ry1); assertEquals("From: Rekisteri line: 89", 1, rekisteri.getRyhmia()); 
    rekisteri.lisaa(ry2); assertEquals("From: Rekisteri line: 90", 2, rekisteri.getRyhmia()); 
    rekisteri.lisaa(ry1); assertEquals("From: Rekisteri line: 91", 3, rekisteri.getRyhmia()); 
    assertEquals("From: Rekisteri line: 92", ry1, rekisteri.annaRyhma(0)); 
    assertEquals("From: Rekisteri line: 93", ry2, rekisteri.annaRyhma(1)); 
    assertEquals("From: Rekisteri line: 94", ry1, rekisteri.annaRyhma(2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta248 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta248() throws SailoException {    // Rekisteri: 248
    String hakemisto = "testiryhma"; 
    File dir = new File(hakemisto); 
    File ftied  = new File(hakemisto+"/ryhmat.dat"); 
    dir.mkdir(); 
    ftied.delete(); 
    rekisteri = new Rekisteri();  // tiedostoja ei ole, tulee poikkeus 
    try {
    rekisteri.lueTiedostosta(hakemisto); 
    fail("Rekisteri: 259 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    alustaRyhma(); 
    rekisteri.setTiedosto(hakemisto);  // nimi annettava koska uusi poisti sen
    rekisteri.tallenna(); 
    rekisteri = new Rekisteri(); 
    rekisteri.lueTiedostosta(hakemisto); 
  } // Generated by ComTest END
}