package ryhma.test;
// Generated by ComTest BEGIN
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import ryhma.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.25 12:25:52 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RyhmatTest {



  // Generated by ComTest BEGIN
  /** testLisaa53 */
  @Test
  public void testLisaa53() {    // Ryhmat: 53
    Ryhmat ryhmaat = new Ryhmat(); 
    Ryhma ryhma1 = new Ryhma(); 
    Ryhma ryhma2 = new Ryhma(); 
    Ryhma ryhma3 = new Ryhma(); 
    Ryhma ryhma4 = new Ryhma(); 
    Ryhma ryhma5 = new Ryhma(); 
    Ryhma ryhma6 = new Ryhma(); 
 
    try {
        ryhmaat.lisaa(ryhma1);
        ryhmaat.lisaa(ryhma2);
        ryhmaat.lisaa(ryhma3); 
        ryhmaat.lisaa(ryhma4); 
        ryhmaat.lisaa(ryhma5); 
        ryhmaat.lisaa(ryhma6);
    } catch (SailoException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    } 
 
    assertEquals("From: Ryhmat line: 67", 6, ryhmaat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista86 */
  @Test
  public void testPoista86() {    // Ryhmat: 86
    Ryhmat ryhmat = new Ryhmat(); 
    Ryhma ryhma1 = new Ryhma(); 
    Ryhma ryhma2 = new Ryhma(); 
    Ryhma ryhma3 = new Ryhma(); 
    ryhma1.rekisteroi(); 
    ryhma2.rekisteroi(); 
    ryhma3.rekisteroi(); 
    int id1 = ryhma1.getTunnusNro(); 
    try {
        ryhmat.lisaa(ryhma1);
        ryhmat.lisaa(ryhma2); 
        ryhmat.lisaa(ryhma3);
    } catch (SailoException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    } 
 
    assertEquals("From: Ryhmat line: 98", 1, ryhmat.poista(id1+1)); 
    assertEquals("From: Ryhmat line: 99", 2, ryhmat.getLkm()); 
    assertEquals("From: Ryhmat line: 100", 1, ryhmat.poista(id1)); 
    assertEquals("From: Ryhmat line: 101", 1, ryhmat.getLkm()); 
    assertEquals("From: Ryhmat line: 102", 0, ryhmat.poista(id1+3)); 
    assertEquals("From: Ryhmat line: 103", 1, ryhmat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta152 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta152() throws SailoException {    // Ryhmat: 152
    Ryhmat ryhmat = new Ryhmat(); 
    Ryhma testi1 = new Ryhma(); 
    testi1.rekisteroi();
    testi1.taytaRyhmaTiedoilla();

    Ryhma testi2 = new Ryhma(); 
    testi2.taytaRyhmaTiedoilla();
    testi2.rekisteroi();
    String hakemisto = "testi"; 
    try {
    ryhmat.lueTiedostosta(hakemisto); 
    fail("Ryhmat: 159 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    String tiedNimi = hakemisto+"/testiryhma"; 
    File ftied = new File(tiedNimi+".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    try {
    ryhmat.lueTiedostosta(tiedNimi); 
    fail("Ryhmat: 165 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    try {
    ryhmat.lisaa(testi1);
    ryhmat.lisaa(testi2);
    } catch (SailoException e) {
    e.printStackTrace(); 
    }
    ryhmat.tallenna(); 
    ryhmat = new Ryhmat(); 
    ryhmat.lueTiedostosta(tiedNimi); 
    assertEquals("From: Ryhmat line: 175", testi1.toString(), ryhmat.anna(0).toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEtsi296 */
  @Test
  public void testEtsi296() {    // Ryhmat: 296
    Ryhmat ryhmat = new Ryhmat(); 
    Ryhma aku = new Ryhma(); 
    aku.rekisteroi(); 
    aku.taytaRyhmaTiedoilla(); 
    try {
        ryhmat.lisaa(aku);
    } catch (SailoException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    } 
    assertEquals("From: Ryhmat line: 302", "1|Ryhma 1|", ryhmat.etsi("Ryhma 1").toString()); 
  } // Generated by ComTest END
}