package ryhma.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ryhma.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.23 14:38:28 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TyotunnitHloTest {


  // Generated by ComTest BEGIN
  /** testGetJasenenNro219 */
  @Test
  public void testGetJasenenNro219() {    // TyotunnitHlo: 219
    Jasen jasen = new Jasen(); 
    jasen.rekisteroi(); 
    assertEquals("From: TyotunnitHlo line: 222", 1, jasen.getTunnusNro()); 
  } // Generated by ComTest END
}