package fxRyhmaKatsaus1.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxRyhmaKatsaus1.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.01.23 12:40:06 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RyhmaMainTest {
}